[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.7"
rocket = "0.5.1"
scraper = "0.20.0"
tokio = { version = "1.40.0",  features = ["rt-multi-thread", "macros"] }
url = "2.3.1"
